### ISSUE TITLE
Better SEO with /robots.txt and /sitemaps.xml

### ISSUE THREAD

**Issue by hejjoe** [tatortrechts/tatortrechts.de#4]
Please enable better crawling of /fall/ID.

**Comment by jfilter** [comment]
Done. I added a /robots.txt as well, but this information is already included in the <head/> of each page.

![Screen Shot 2021-02-21 at 17 36 13](https://user-images.githubusercontent.com/3450307/108631699-6b923a00-746b-11eb-8a13-c8f6ecc5e74e.png)



https://tatortrechts.de/sitemap.xml
